spring:
  application:
    name: saf-restaurant
  datasource:
    url: jdbc:postgresql://localhost:5432/saf_restaurant
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

saf:
  inventory:
    url: http://inventory-service
    check-path: /api/inventory/check
    enabled: true
  restaurant:
    pending-timeout: 30s
    pending-scan-interval: 5000

logging:
  file:
    name: logs/restaurant.log  # Le fichier où les logs s'écriront
  level:
    root: INFO
    com.saf: INFO
    com.saf.core1: INFO
    org.hibernate: WARN
    org.springframework: WARN
    com.netflix: WARN
    org.apache: WARN
  pattern:
    # Le pattern magique qui récupère l'ID de l'acteur (%X{actorId})
    # Attention aux guillemets "" obligatoires en YAML à cause des caractères spéciaux
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{36}] [Actor:%X{actorId}] - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%logger{36}] [Actor:%X{actorId}] - %msg%n"
